const DECREMENT_SESSION = "DECREMENT_SESSION";
const INCREMENT_SESSION = "INCREMENT_SESSION";
const START_SESSION = "START_SESSION";

const sessionActions = {
  INCREMENT_SESSION,
  DECREMENT_SESSION,
  START_SESSION
};

export default sessionActions;
